version: 0.2
phases:
  install:
    commands:
      - echo "Installing Terraform"
      - curl -O https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_linux_amd64.zip
      - unzip terraform_1.5.0_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform --version
  pre_build:
    commands:
      - echo "Initializing Terraform"
      - terraform init -backend-config="bucket=$TERRAFORM_BUCKET" -backend-config="dynamodb_table=$TERRAFORM_DYNAMODB_TABLE"
  build:
    commands:
      - echo "Packaging the Lambda function code"
      - zip metric_app.zip metric_app.py
      - echo "Applying Terraform configuration"
      - terraform apply -auto-approve
  post_build:
    commands:
      - echo "Build completed"
artifacts:
  files:
    - metric_app.zip
